### ISSUE TITLE
ttf-pragmatapro AUR package

### ISSUE THREAD

**Issue by baodrate** [wezm/aur#1]
Hi @wezm! Sorry for the insanely late response. Gonna quote my comment in the AUR package:

> I hadn't used arch for a few years and just got back into it. I also don't use pragmatapro anymore. Would you like to takeover this package?

for reference:

https://aur.archlinux.org/packages/ttf-pragmatapro/

**Comment by ShayBox** [comment]
Bump, some convo going on in the comments, if you're willing to take over
https://aur.archlinux.org/packages/ttf-pragmatapro/
