### ISSUE TITLE
xorg-font-utils removed

### ISSUE THREAD

**Issue by iyzg** [wezm/aur#3]
Arch dropped in the package xorg-font-utils which was needed for ttf-pragmata-pro and included the list of packages to replace it [here](https://www.archlinux.org/todo/removal-of-xorg-font-utils-transitional-package/), but the font still has xorg-font-utils as a required package.

**Comment by wezm** [comment]
Thanks for the head up. I have removed the PKGBUILD from this repo and updated the AUR package I maintain. https://aur.archlinux.org/packages/ttf-pragmatapro
